global:
  scrape_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090

  - job_name: 'rest'
    dns_sd_configs:
      - names: ['tasks.rest']
        type: A
        port: 3000