{
 "title": "Rest service",
 "description": "Metrics of the REST service that accepts the call, pushes into queue, waits for worker to process, and returns the result.",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(rest_queued_count[$__rate_interval])",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "sum(increase(rest_queued_count[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(rest_success_total[$__rate_interval])",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "sum(increase(rest_success_total[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "increase(rest_failure_total[$__rate_interval])",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "sum(increase(rest_failure_total[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Timings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Duration from proxy receive to Redis push",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(rest_proxy_queue_duration_ms_bucket[$__rate_interval]))",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(rest_proxy_queue_duration_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duration from Redis push to worker response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(rest_worker_process_duration_ms_bucket[$__rate_interval]))",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(rest_worker_process_duration_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duration from worker response to proxy response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(rest_proxy_wait_duration_ms_bucket[$__rate_interval]))",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(rest_proxy_wait_duration_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Full roundtrip duration from receive to response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(rest_total_duration_ms_bucket[$__rate_interval]))",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(rest_total_duration_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}