{
 "title": "Rest service",
 "description": "Metrics of the REST service that accepts the call, pushes into queue, waits for worker to process, and returns the result.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(rest_success_total[$__rate_interval])",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "sum(increase(rest_success_total[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(rest_failure_total[$__rate_interval])",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "sum(increase(rest_failure_total[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "increase(rest_queued_count[$__rate_interval])",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "sum(increase(rest_queued_count[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Timings - Stacked and Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total roundtrip time from REST request to REST response (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(duration_total_roundtrip_ms_bucket[$__rate_interval]))",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(duration_total_roundtrip_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Timing stacked",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(duration_rest_request_to_queue_push_ms_bucket[$__rate_interval])\r\n  )\r\n)\r\n",
     "legendFormat": "Request to Push (REST)"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(duration_rest_push_to_worker_pull_ms_bucket[$__rate_interval])\r\n  )\r\n)\r\n",
     "legendFormat": "Push (REST) to Pull (Worker)"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(duration_worker_pull_to_worker_push_ms_bucket[$__rate_interval])\r\n  )\r\n)\r\n",
     "legendFormat": "Pull (Worker) to Push (Worker)"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(duration_worker_push_to_rest_pull_ms_bucket[$__rate_interval])\r\n  )\r\n)\r\n",
     "legendFormat": "Push (Worker) to Pull (REST)"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(duration_rest_pull_to_rest_response_ms_bucket[$__rate_interval])\r\n  )\r\n)\r\n",
     "legendFormat": "Pull (REST) to HTTP response"
    }
   ]
  },
  { "title": "Timings - detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Duration from REST request to Redis push (REST) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(duration_rest_request_to_queue_push_ms_bucket[$__rate_interval]))",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(duration_rest_request_to_queue_push_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duration from Redis push (REST) to Redis pull (Worker) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(duration_rest_push_to_worker_pull_ms_bucket[$__rate_interval]))",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(duration_rest_push_to_worker_pull_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duration from Redis pull (Worker) to Redis push (Worker) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(duration_worker_pull_to_worker_push_ms_bucket[$__rate_interval]))",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(duration_worker_pull_to_worker_push_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duration from Redis push (Worker) to Redis pull (REST) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(duration_worker_push_to_rest_pull_ms_bucket[$__rate_interval]))",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(duration_worker_push_to_rest_pull_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duration from Redis pull (REST) to HTTP response (REST) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(duration_rest_pull_to_rest_response_ms_bucket[$__rate_interval]))",
     "legendFormat": "by {{instance}}"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(duration_rest_pull_to_rest_response_ms_bucket[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}